version: "3.8"

services:
  web:
    volumes:
      - static_volume:/app/backend/src/mediafields
      - ./services/backend/htmlcov:/app/backend/htmlcov
    ports:
      - "8000:8000"

  frontend:
    volumes:
      - ./services/frontend/src:/app/src
    ports:
      - "5173:5173"

  db:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
